### ISSUE TITLE
blink method should preserve brightness

### ISSUE THREAD

**Issue by eadmaster** [bremme/arduino-tm1637#14]
the blink method should preserve the current brightness rather than resetting to 100.
This way if i reduce the brightness before the calling "begin()" it is not reset.

**Comment by bremme** [comment]
Thanks for reporting this issue, I agree! This should not be that hard to add to the library. Update: I just fixed it by this commit 019612dbd8be4c9ad1b2207eb8035a4f8b5496ff. I probably should update the README as well, the full signature for the `blink()` method is:

```c++
void    blink(uint8_t blinkDelay = TM1637_DEFAULT_BLINK_DELAY, uint8_t repeats = TM1637_DEFAULT_BLINK_REPEAT, uint8_t maxBacklight=100, uint8_t minBacklight=0);
```
So you can set the following blink options: delay (how long on/off time in ms), repeats, maxBacklight (how bright is on) and minBacklight (how bright is off).

Hope this helps, closing this issue for now.
