### ISSUE TITLE
printraw at segment 1

### ISSUE THREAD

**Issue by intel2004** [bremme/arduino-tm1637#23]
i have to create a custom bar, so instead of continuing clear of display i want to crewate printraw to clear a single char.
if i use:
display.printRaw(128,2);
i clear the third position of the display correctly, but if i set the second position:
display.printRaw(128,1);
it view the decimal point! so i'm trying to put:
display.printRaw(0,1);
but there is a compiling error: there is a solution?

**Comment by bremme** [comment]
This is expected behavior I think. 128 is B1000 0000, the last bit is often connected to the dot or color depending on the display. The compilation error occurs because the call is ambiguous. You can solve this by passing a value of the right type:

```c++
    unsigned char rawValue = 0;
    display.printRaw(rawValue, 1);
```

or

```c++
display.printRaw(uint8_t(0), 0);
```
hope this helps.
