### ISSUE TITLE
Publish to PlatformIO

### ISSUE THREAD

**Issue by 6wheels** [bremme/arduino-tm1637#31]
Hi,

I use PlatformIO with VSCode to easily build and manage my projects.
It would be great if you could publish your lib to it as well.
I see that your project already has a library.json file, so it should be straight forward.
Here is a link to the platformio docs for publishing: https://docs.platformio.org/en/latest/librarymanager/creating.html

Thanks.

**Comment by per1234** [comment]
This library has a library.properties file, not library.json. But that's fine because [PlatformIO also supports library.properties as a library manifest](https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#description).

**Comment by vazquezjm** [comment]
Done!
![AwesomeScreenshot-2019-07-22-2024-2019-07-22-20-07-61](https://user-images.githubusercontent.com/5269397/61671667-012d7c80-acbf-11e9-8b4b-5bf1f1909a8d.png)

**Comment by 6wheels** [comment]
Great! Thanks!
