### ISSUE TITLE
Rotary Encoder and Display

### ISSUE THREAD

**Issue by gitandrewd** [bremme/arduino-tm1637#32]
Hi,

Firstly thanks for this great Library!

I am currently using it with Catalex TM1637 with a rotary encoder. The issue I am having is that every time I scroll up from 90 pass 100 then down again below 99, the third segment remains at 0. So 99 and anything below becomes 990. Is there any way for me to clear than third segment once it drops below 99.

Thanks for your time!
Dave

**Comment by Amritpal101** [comment]
You can use it with this logic   
  

  
If (value  <=99){
  
  
display.setCurser(0,0);
  
displayPrint(value);
  
  
display.setCurser(0,2)
  
displayPrint(“    ”);
  
}else if(value  >=100){
  
display.setCurser(0,0);
  
displayPrint(value);
  
}
  
  
  
  
  
  
  
  Amritpal Singh
  
  
  
  

  
  
>

**Comment by gitandrewd** [comment]
Worked Perfect! Thanks Amritpal for the quick reply :)
