### ISSUE TITLE
type error bouncingBall function name

### ISSUE THREAD

**Issue by hznupeter** [bremme/arduino-tm1637#44]
Line 58 in https://github.com/bremme/arduino-tm1637/blob/master/src/SevenSegmentFun.h  void bouchingBall(uint16_t moves, uint16_t d, bool runForever = false);
Line 187in https://github.com/bremme/arduino-tm1637/blob/master/src/SevenSegmentFun.cpp  void  SevenSegmentFun::bouncingBall(uint16_t moves, uint16_t d, bool runForever) {

the function name is different. bouchingBall & bouncingBall

**Comment by bremme** [comment]
Can't believe I missed that. Should be corrected in the v1.1.1 release. Sorry for the inconvenience and thanks for pointing that out.
